### ISSUE TITLE
heaterCooler 下操作没有任何反应

### ISSUE THREAD

**Issue by BaranWang** [LASER-Yi/homebridge-mi-acpartner#13]
climate 下操作一切正常，改成 heaterCooler 后任何操作都没有反馈
美的方案3

**Comment by LASER-Yi** [comment]
climate下是否使用了自定义的信号，因为heatercooler不会支持自定义信号的功能，然后能否让Homebridge以-D方式启动，并截图发送时的日志。

**Comment by qqshfox** [comment]
有同样的问题。修了 #15 以后，通过Home操作会有`Waiting for Sync state, please try again`的log，从代码上看是没有`model`，具体要晚上回去看下详细的日志和debug。

**Comment by qqshfox** [comment]
看了代码和日志，看上去是用global device的方式还没有调试过吧？我把ip和token放到accessory里以后，就有model了。
但是，接下来就报`[ERROR]Sync failed, error: TypeError: Cannot read property 'error' of undefined`的错，看上去是log有问题，估计还是this的问题，没有仔细看。然后看找到这个错的源头，是

```
in catch TypeError: this.TargetHeaterCoolerState.updateValue is not a function
    at p2.device.call.then.ret (/usr/local/lib/node_modules/homebridge-mi-acpartner/accessories/heaterCooler.js:316:46)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
具体的location可以忽略，我有加过一些log。看上去`Characteristic.TargetHeaterCoolerState`有问题？看到 KhaosT/HAP-NodeJS#421 ，对比原来的`climate`，从`TargetHeatingCoolingState`改为`TargetHeaterCoolerState`是有意而为之的么？

**Comment by LASER-Yi** [comment]
是的，这两个配件本质上还是有区别的，你看看0.6.x版本之后还有没有这个问题

**Comment by lvhe19880210** [comment]
beta最新版 ，预设格力2， 目前也是这个问题

**Comment by lvhe19880210** [comment]
如果是稳定版，则会报Sync failed! Error: user ack timeout
    at Object.reject (/usr/local/lib/node_modules/homebridge-mi-acpartner/node_modules/miio/lib/device.js:217:13)
    at Device._onMessage (/usr/local/lib/node_modules/homebridge-mi-acpartner/node_modules/miio/lib/device.js:108:8)
    at Socket.emit (events.js:210:5)

**Comment by lvhe19880210** [comment]
对了 我的设备是79那款2代网关
