### ISSUE TITLE
ver 0.5.1 problem

### ISSUE THREAD

**Issue by cjinsider** [LASER-Yi/homebridge-mi-acpartner#17]
/usr/local/lib/node_modules/homebridge-mi-acpartner/accessories/heaterCooler.js:42
<<<<<<< HEAD
^^

SyntaxError: Unexpected token <<
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-acpartner/index.js:8:1)
please help me. Homebridge dont start

**Comment by cuihaijun** [comment]
me too

**Comment by KebinSen** [comment]
just back to v0.5.0

**Comment by LASER-Yi** [comment]
Fixed. Please update to 0.5.2
