### ISSUE TITLE
与mi-aqara同时运行时导致超时错误

### ISSUE THREAD

**Issue by phenix13** [LASER-Yi/homebridge-mi-acpartner#19]
安装mi-aqara及伴侣插件运行后mi-aqara报错[ERROR]Error:timeout:{“cmd”“write”，“model”：“ctrl_neutrall”,"sid":"xxxxxxxxx","date":"{\"channel_0\":\"off"\",\"key\":\"xxxxxxx\"}"}，编辑config去掉伴侣后mi-aqara正常
分桥运行2个插件，伴侣插件桥未启动时mi-aqara相应正常，伴侣桥启动后mi-aqara设备响应，但是无反馈，设备总菊花，用siri开灯，实际灯已经打开，但siri反馈无响应

**Comment by LASER-Yi** [comment]
今天查了这个问题，发现是miio的原因，使用0.14.1版本的miio就不会出现这个问题了

**Comment by Raccooon** [comment]
超时错误依旧存在。
在readme中，您已经更新到了0.15.6
我应该是使用哪个版本的miio呢？
`[7/13/2018, 3:21:22 AM] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"gateway","sid":"7811dcdc2a79","data":"{\"rgb\":1694498815, \"key\": \"0edfda91c24c5a4e570f0e8dc13261ff\"}"}
[7/13/2018, 3:21:22 AM] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"gateway","sid":"7811dcdc2a79","data":"{\"rgb\":1694498815, \"key\": \"0edfda91c24c5a4e570f0e8dc13261ff\"}"}
    at Timeout.setInterval (/usr/lib/node_modules/homebridge-mi-aqara/index.js:399:27)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[7/13/2018, 3:21:22 AM] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"gateway","sid":"7811dcdc2a79","data":"{\"rgb\":1694498815, \"key\": \"0edfda91c24c5a4e570f0e8dc13261ff\"}"}
[7/13/2018, 3:21:22 AM] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"gateway","sid":"7811dcdc2a79","data":"{\"rgb\":1694498815, \"key\": \"0edfda91c24c5a4e570f0e8dc13261ff\"}"}
    at Timeout.setInterval (/usr/lib/node_modules/homebridge-mi-aqara/index.js:399:27)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[7/13/2018, 3:21:22 AM] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"gateway","sid":"7811dcdc2a79","data":"{\"rgb\":1694498815, \"key\": \"0edfda91c24c5a4e570f0e8dc13261ff\"}"}
[7/13/2018, 3:21:22 AM] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"gateway","sid":"7811dcdc2a79","data":"{\"rgb\":1694498815, \"key\": \"0edfda91c24c5a4e570f0e8dc13261ff\"}"}
    at Timeout.setInterval (/usr/lib/node_modules/homebridge-mi-aqara/index.js:399:27)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[7/13/2018, 3:21:22 AM] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"gateway","sid":"7811dcdc2a79","data":"{\"rgb\":1694498815, \"key\": \"0edfda91c24c5a4e570f0e8dc13261ff\"}"}
[7/13/2018, 3:21:22 AM] [MiAqaraPlatform] [ERROR]Error: timeout: {"cmd":"write","model":"gateway","sid":"7811dcdc2a79","data":"{\"rgb\":1694498815, \"key\": \"0edfda91c24c5a4e570f0e8dc13261ff\"}"}
    at Timeout.setInterval (/usr/lib/node_modules/homebridge-mi-aqara/index.js:399:27)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[7/13/2018, 3:22:15 AM] [XiaoMiAcPartner] Sync -----------------------------
[7/13/2018, 3:22:15 AM] [XiaoMiAcPartner] Accessory -> Ac Partner
[7/13/2018, 3:22:15 AM] [XiaoMiAcPartner] Model -> 0100011272
[7/13/2018, 3:22:15 AM] [XiaoMiAcPartner] Active -> 0
[7/13/2018, 3:22:15 AM] [XiaoMiAcPartner] Mode -> 1
[7/13/2018, 3:22:15 AM] [XiaoMiAcPartner] Temperature -> 26
[7/13/2018, 3:22:15 AM] [XiaoMiAcPartner] RotationSpeed -> 3
[7/13/2018, 3:22:15 AM] [XiaoMiAcPartner] SwingMode -> 0
[7/13/2018, 3:22:15 AM] [XiaoMiAcPartner] LED -> 0
[7/13/2018, 3:22:15 AM] [XiaoMiAcPartner] -----------------------------------
`
